### PR TITLE
Add support for multisite installs using subdirectories

### PR DESCRIPTION
**Pull request by hughbris**
Have not included subdomain flavour of Grav multisites because it requires wildcard subdomains and I didn't want to go there. I don't use these as yet, anyway. The subdomain setup file is included just in case it's useful.

### CODE REVIEW

**Comment by dsavell** [comment]
Hey @hughbris Happy new year!

Thanks for this, I have left some reviews before merging just more of a cleanup, but happy to get this merged before I build 1.6.31, will give it a few days, then I will merge, and cleanup after.

**Comment by hughbris** [comment]
Too slow! Thank you anyway. Where in the Github UI do I find your reviews, just for my enlightenment?

**Comment by dsavell** [comment]
Hey @hughbris,

This should be part of this PR, have a look at files changed you should be able to see my comments on the lines in question.

**Comment by hughbris** [comment]
I can't see them, never mind.

**Pull request merged**
