### PR TITLE
Add an option for non-production robots.txt file

### PR DESCRIPTION
**Pull request by hughbris**
This is pretty much straight out of [my own Caddy-based grav image](https://github.com/hughbris/grav-daddy/blob/5a954c0afdfc14c1d005b5dd6cb787f21aecdf4e/init/init-grav#L51). I still use your nginx image for at least one multisite because the multisite setup does not seem to work under Caddy.

I find it an invaluable option for staging environments so that they won't be indexed. (I have now given up trying to protect staging environments with HTTP auth and explaining that to clients!).

Of course, the `/robots.txt` file sits above Grav's `user` folder and is out of reach of the standard bind mounts.

Other ways this could be achieved:
* bind mount the robots.txt file
* General recipe: [Display different robots.txt contents for different environments](https://learn.getgrav.org/17/cookbook/general-recipes#display-different-robots-)

So, while not essential, this seems simplest, and I make use of it plenty.

### CODE REVIEW

**Comment by dsavell** [comment]
Heya, if your able to rebase this code, I can get it merged for the next release.

**Comment by hughbris** [comment]
Thanks David, do you have a timeframe in mind?

**Comment by dsavell** [comment]
Can probably look at it tomorrow rebuild the same version if you need it?

**Comment by hughbris** [comment]
Sorry you are probably asking a straightforward question, but it's too much to get my head around now. I will see if I can rebase by tomorrow (actually tomorrow is Saturday here, you probably mean today!). If not, flag it if it's too tricky. We'll get the next release. No people banging at the door, I'm pretty sure :D

**Comment by dsavell** [comment]
Wait we’re not all UTC? ;) haha no problem will keep an eye on the PR over
the next few days I will wait :)

**Comment by hughbris** [comment]
Hmm, a blank line. Spurious conflict! :)

**Comment by dsavell** [comment]
Merged & Built

**Pull request merged**
